# Minimal Jekyll config for bimleshky.github.io - Focused Structure

title: "Bimlesh Kumar Yadav | Portfolio & Insights"
description: "Lab Assistant | IISER Kolkata Alumnus | UPSC Aspirant | Science Educator"
url: "https://bimleshky.github.io"
baseurl: ""
repository: "bimleshky/bimleshky.github.io"
locale: "en-US"
timezone: "Asia/Kolkata"

author:
  name: "Bimlesh Kumar Yadav"
  email: "bimleshky@gmail.com"
  linkedin: "bimlesh-kumar-yadav"
  github: "bimleshky"

# Navigation structure for main sections
navigation:
  - title: "Home"
    url: "/"
  - title: "About Me"
    url: "/about/"
  - title: "Academic & Professional Journey"
    url: "/journey/"
  - title: "UPSC Journey"
    url: "/upsc/"
  - title: "Portfolio / Projects"
    url: "/portfolio/"
  - title: "Teaching Resources"
    url: "/resources/"
  - title: "Blog / Insights"
    url: "/blog/"
  - title: "Highlights & Achievements"
    url: "/achievements/"
  - title: "UPSC Resources"
    url: "/upsc-resources/"
  - title: "Contact / Connect"
    url: "/contact/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  resources:
    output: true
    permalink: /resources/:path/
  blog:
    output: true
    permalink: /blog/:path/
  achievements:
    output: true
    permalink: /achievements/:path/
  upsc-resources:
    output: true
    permalink: /upsc-resources/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: resources
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: blog
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: achievements
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: upsc-resources
    values:
      layout: single
      author_profile: true

# Plugins for essential functionality
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

# Include these folders for content
include:
  - _portfolio
  - _resources
  - _blog
  - _achievements
  - _upsc-resources
  - _pages

# Exclude unnecessary files/folders
exclude:
  - node_modules
  - vendor
  - tmp
  - .sass-cache
  - .jekyll-assets-cache
  - .github

permalink: /:categories/:title/

# Social media/contact - for sidebar/footer/contact page
contact_links:
  email: "bimleshky@gmail.com"
  linkedin: "https://linkedin.com/in/bimlesh-kumar-yadav"
  github: "https://github.com/bimleshky"

# Custom - call-to-action/contact form can be implemented in /contact/ page
